# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source "$XDG_CONFIG_HOME/bash/rc"

[[ -n $DISPLAY ]] && xrdb -load "$XDG_CONFIG_HOME/xterm/.Xresources" >/dev/null 2>&1


# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
