set number
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set hlsearch
set incsearch
set ttyfast

set mouse=a
set wildmenu
set wildmode=full

syntax on
colorscheme slate
filetype plugin indent on

set viminfo+=n$XDG_CACHE_HOME/vim/viminfo

map <F5> :! make
